import type { GetServerSideProps, NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.scss'
import Link from 'next/link'
import Image from 'next/image';
import {useSelector} from "react-redux";
import { selectUser } from './../src/store';
import costumAxios from "../utils/axios";
import useSWR from "swr";
import { SpinnerDotted } from 'spinners-react';



const fetcher = async() => {
  const res =  await costumAxios.get("/");
  return res.data
}



// types
interface VideoPrewData{
  id:string,
  title:string,
  folder:string,
  date:string,
  duration:{minute:number , second:number},
  views:number,
  userID:Number
}


interface HomeProps{
  videPrewData:[VideoPrewData]
}

const myLoader=({src}:any)=>{
  return `${process.env.NEXT_PUBLIC_REMOTE}/watch/thumb/${src}`;
}
const displayImage = (file:VideoPrewData) =>{
  console.log(file)
  let date = new Intl.DateTimeFormat('en-US', { year: 'numeric', month: '2-digit', day: '2-digit' }).format(+file.date)
   return <div key={file.id}  id={file.id}>
             <Link href={`watch/${file.id}`}>
               <a href="#">
                 <Image loader={myLoader} height={200} width={200}
                      src={`${file.id}`} alt={file.id}
                  />
               </a>
             </Link>
             <span>{file.title}</span>
               <span>{date}</span>
               <span>{file.duration.minute}:{file.duration.second}</span>
           </div>
}

const onClickLogout =  async (e:React.MouseEvent<HTMLParagraphElement>) =>{
  
}


const getVideos = () =>{
  const {data , error} = useSWR('/' , fetcher)
  return {
    videos:data,
    isLoading: !error && !data,
    isError:error
  }
}

const Home: NextPage<HomeProps> = () => {
  
  const user = useSelector(selectUser).user

  const {videos,isLoading,isError} = getVideos();

 



  return (
    <div className={styles.container}>
      <Head>
        <title>watchit</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>

            {
              isLoading ? <SpinnerDotted/> :
              videos &&  videos.map((d:VideoPrewData) => {
                return displayImage(d);
              }) 
            }
            
            
      </main>

      <footer className={styles.footer}>
        
      </footer>
    </div>
  )
}




export default Home
